export const periods = [
  {
    id: 1,
    number: "01",
    title: "Primer Período",
    dateRange: "Enero – Marzo",
    color: "#2558f4",
    gradient: "linear-gradient(135deg, #1d40b0 0%, #2c5cf6 100%)",
    lightBg: "#eef2ff",
    accent: "#5b82f6",
    emoji: "🌱",
    topics: ["Greetings & Farewells", "Colors & Shapes", "Numbers 1–10"],
    description:
      "El estudiante reconoce y usa saludos básicos en inglés, identifica colores y figuras geométricas simples, y cuenta del 1 al 10 de forma oral y escrita.",
    activities: 8,
    completed: 3,
    status: "en progreso",
  },
  {
    id: 2,
    number: "02",
    title: "Segundo Período",
    dateRange: "Abril – Junio",
    color: "#059669",
    gradient: "linear-gradient(135deg, #065f46 0%, #059669 100%)",
    lightBg: "#ecfdf5",
    accent: "#34d399",
    emoji: "🌿",
    topics: ["Family Members", "Body Parts", "Classroom Objects"],
    description:
      "El estudiante nombra los miembros de su familia, identifica las partes del cuerpo y reconoce los objetos más comunes del salón de clases en inglés.",
    activities: 9,
    completed: 0,
    status: "próximo",
  },
  {
    id: 3,
    number: "03",
    title: "Tercer Período",
    dateRange: "Julio – Septiembre",
    color: "#d97706",
    gradient: "linear-gradient(135deg, #92400e 0%, #d97706 100%)",
    lightBg: "#fffbeb",
    accent: "#fbbf24",
    emoji: "🌻",
    topics: ["Animals & Pets", "Food & Drinks", "My Home"],
    description:
      "El estudiante describe animales domésticos y salvajes, menciona alimentos y bebidas de su preferencia, y describe los espacios básicos de su hogar.",
    activities: 10,
    completed: 0,
    status: "próximo",
  },
  {
    id: 4,
    number: "04",
    title: "Cuarto Período",
    dateRange: "Octubre – Diciembre",
    color: "#7c3aed",
    gradient: "linear-gradient(135deg, #4c1d95 0%, #7c3aed 100%)",
    lightBg: "#f5f3ff",
    accent: "#a78bfa",
    emoji: "🌟",
    topics: ["Actions & Verbs", "Weather & Seasons", "Short Sentences"],
    description:
      "El estudiante expresa acciones cotidianas con verbos básicos, describe el clima y las estaciones del año, y construye oraciones simples en inglés.",
    activities: 10,
    completed: 0,
    status: "próximo",
  },
];